LimeChain/RollupCodes

- src/docs/optimism.mdx
**Detailed description**:
* https://community.optimism.io/docs/developers/build/differences/#opcode-differences
**Which issue(s) this PR fixes**:
Fixes #none
> feat(optimism/opcodes): add `PUSH0`

- src/docs/scroll.mdx
> Update scroll text.mdx

- src/docs/arbitrum-one.mdx
- src/docs/base.mdx
- src/docs/linea.mdx
- src/docs/optimism.mdx
- src/docs/polygon-zkevm.mdx
- src/docs/scroll.mdx
- src/docs/taiko.mdx
- src/docs/zksync-era.mdx
The correct way to write the project name is with capital letters -> L2BEAT.
> Update the L2BEAT name

- src/docs/taiko.mdx
There is a new Taiko testnet (alpha-6) but it doesn't add any of the Cancun features ([source](https://taiko.mirror.xyz/a5SHfg_V16TOVS_LpFgrbfgi_shwC5HhpPZ5C2hnuFo))
> feat: update Taiko page with the missing Cancun features

- src/docs/base.mdx
Removes PUSH0 opcode from unsupported in Base
> fix: remove PUSH0 opcode from unsupported in Base

- src/docs/linea.mdx
- Updates Linea RPC endpoints
- Fixes #101
> feat: update Linea RPC endpoints

- src/components/Labels/index.tsx
- src/docs/taiko.mdx
Updates Taiko's status to mainnet and changes the Rollup’s State Contract on L1 address
> feat: change Taiko to mainnet

- src/docs/linea.mdx
Changes block time to 2 seconds. [source](https://docs.linea.build/developers/linea-version#alpha-v33)
> feat: update linea info for alpha v3.3

- src/docs/taiko.mdx
* fix taiko outdated bridge url
> fix(taiko): bridge url

- src/docs/scroll.mdx
Updates Scroll's information for the [Curie upgrade](https://github.com/scroll-tech/go-ethereum/releases/tag/scroll-v5.4.2)
> feat: update information for Scroll's Curie upgrade

- src/docs/base.mdx
- src/docs/optimism.mdx
- The Fjord upgrade adds the `p256Verify` precompile. [Source](https://specs.optimism.io/fjord/overview.html#execution-layer)
> feat: update Optimism and Base info for the Fjord upgrade (Activates on 10.07.24)

- src/docs/arbitrum-one.mdx
https://docs.arbitrum.io/build-decentralized-apps/arbitrum-vs-ethereum/solidity-support
> feat(arb/opcodes): difficulty & prevrandao

- src/docs/taiko.mdx
- Taiko's sequencing is now fully permissionless ([source](https://taiko.mirror.xyz/_oKlnpzKSOxGILyy4WlvpUmYEqD7BFxzmRo3XETlJqE))
> feat(taiko): Sequencing is permmissionless

- src/docs/taiko.mdx
- Taiko uses ZK proofs on mainnet ([source](https://taiko.mirror.xyz/4c6VNhjKLHOMaNKRryyKHkiHcWx7caRax_mC0jTr-sY))
> feat(taiko): zk proofs

- src/docs/scroll.mdx
It seems that "6 point pairs" is not a limit anywhere.
> fix(scroll): a typo

- src/docs/arbitrum-one.mdx
change old link to a new one
you are welcome
> new Update arbitrum-one.mdx

- src/components/MDXShortcodes/index.tsx
- src/docs/base.mdx
- src/docs/blast.mdx
- src/docs/optimism.mdx
- Enables HTML formatting in Tooltip component
- Updates the sequencing frequency for all Optimism rollups
- Updates the gas target for all Optimism rollups
- Updates the "Rollup's state contract" description and contract address for Optimism and Base
- Updates the fraud proof information for Base
- Updates messaging cost for all Optimism rollups
- Updates tooling information for all Optimism rollups
> feat(opstack): Update state contract

- src/docs/base.mdx
- src/docs/blast.mdx
- src/docs/ink.mdx
- src/docs/optimism.mdx
- src/docs/scroll.mdx
- src/docs/soneium.mdx
- src/docs/world-chain.mdx
- src/docs/zircuit.mdx
- src/pages/[slug]/index.tsx
- Fixes building the final chainspec version
- Correctly capitalizes the "Block Time" parameter
> fix: Prague upgrade

- src/docs/world-chain.mdx
> fix(world-chain): overview

- src/docs/abstract.mdx
- src/docs/arbitrum-one.mdx
- src/docs/base.mdx
- src/docs/blast.mdx
- src/docs/ink.mdx
- src/docs/linea.mdx
- src/docs/optimism.mdx
- src/docs/polygon-zkevm.mdx
- src/docs/scroll.mdx
- src/docs/soneium.mdx
- src/docs/taiko.mdx
- src/docs/world-chain.mdx
- src/docs/zircuit.mdx
- src/docs/zksync-era.mdx
- Fixes the values for most messaging cost parameters
- Adds delivery method for some rollups
> fix: messaging info for all rollups
