LimeChain/RollupCodes

- src/docs/arbitrum-one.mdx
With [ArbOS version 11](https://forum.arbitrum.foundation/t/aip-arbos-version-11/19696), Arbitrum now supports the Shanghai L1 upgrade, which includes the PUSH0 OPCODE
> feat: push0 support in Arbitrum

- src/docs/zksync-era.mdx
This PR adds the following changes:
1. `block.number` and `block.timestamp` now return the values for the L2 block, instead of the batch ([source](https://github.com/zkSync-Community-Hub/zksync-developers/discussions/87))
2. `ecrecover` now behaves as on Ethereum ([source](https://github.com/zkSync-Community-Hub/zksync-developers/discussions/399))
3. added `Remix plugin`, `web3.js zkSync plugin` and `foundry-zksync` to the tools section ([source1](https://github.com/zkSync-Community-Hub/zksync-developers/discussions/312) [source2](https://github.com/zkSync-Community-Hub/zksync-developers/discussions/399))
> feat: timestamp in zkSyncEra behaves like on ETH

- src/docs/polygon-zkevm.mdx
Update the polygon zkEVM data
1. [v0.4.0](https://github.com/0xPolygonHermez/zkevm-node/releases/tag/v0.4.0)
2. add debug_traceBatchByNumber RPC endpoint
3. zkevm_getNativeBlockHashesInRange RPC endpoint
2. [v0.4.5](https://github.com/0xPolygonHermez/zkevm-node/releases/tag/v0.4.5)
1. add zkevm_estimateFee RPC endpoint
3. [v0.5.0](https://github.com/0xPolygonHermez/zkevm-node/releases/tag/v0.5.0)
1. add support for ecAdd, ecMul, ecPairing and Sha256 precompiles
4. [v0.5.13](https://github.com/0xPolygonHermez/zkevm-node/releases/tag/v0.5.13)
1. add zkevm_estimateGasPrice RPC endpoint
2. add zkevm_estimateCounters RPC endpoint
> feat: update polygon zkEVM data

- src/docs/scroll.mdx
1. L1 -> L2 messaging cost has been decreased by up to 50% ([source](https://scroll.io/blog/protocol-upgrade-bridging-cost-reduction))
2. `L2GasPriceOracle` was merged with `L1MessageQueue` into `L1MessageQueueWithGasPriceOracle` ([source](https://scroll.io/blog/protocol-upgrade-bridging-cost-reduction))
3. Scroll has not added the new opcodes from the Cancun update
> feat: update scroll data

- src/docs/linea.mdx
Updates the Linea information with the latest updates (Alpha v2 and Alpha v3) and adds the missing Cancun features ([source](https://docs.linea.build/build-on-linea/linea-version))
1. Added `linea_estimateGas` endpoint (February 19)
2. Block time reduced to 3 seconds (alpha v3)
> feat: update Linea's page with the Cancun info

- src/components/MDXShortcodes/index.tsx
- src/docs/arbitrum-one.mdx
- src/docs/base.mdx
- src/docs/linea.mdx
- src/docs/optimism.mdx
- src/docs/polygon-zkevm.mdx
- src/docs/scroll.mdx
- src/docs/taiko.mdx
- src/docs/zksync-era.mdx
Renames the `Finality` parameter to `Objective Finality`. Also adds a title attribute to the `Copy` component in order to show the full system contract/precompile address on hover.
> Feat: change finality wording

- src/docs/scroll.mdx
- removes SHA-256 precompile from unsupported for Scroll
- Fixes #100
> feat(Scroll): remove SHA-256 precompile from unsupported

- src/docs/taiko.mdx
Add missing rpc api calls:
* `taiko_getSyncMode` - [link](https://github.com/taikoxyz/taiko-geth/blob/taiko/eth/taiko_api_backend.go#L64)
* `taikoAuth_txPoolContent` - [link](https://github.com/taikoxyz/taiko-geth/blob/taiko/eth/taiko_api_backend.go#L79), beneficial for the whole L2 execution.
> feat(taiko): missing rpc api calls

- src/docs/scroll.mdx
scroll already supports `p256Verify`. see https://github.com/scroll-tech/go-ethereum/pull/798
> scroll: add `p256Verify` precompile

- src/docs/scroll.mdx
This PR fixes an info error since Scroll has supported Type-1 transactions.
An example: https://scrollscan.com/tx/0xcccf32b0390ec1a35c94aabab8aecd6e699490c86968927258f4f9a5c7637e7e
> fix: add Type-1 transactions in supported transactions

- src/docs/arbitrum-one.mdx
- Marks `timestamp` opcode as supported
> feat(arbitrum/opcodes): timestamp

- src/docs/base.mdx
- src/docs/blast.mdx
- src/docs/optimism.mdx
- Changes `COINBASE`, `TIMESTAMP` and `NUMBER` to unmodified for `Base`, `Blast` and `Optimism`
- Renames `DIFFICULTY` to `PREVRANDAO` and updates its information for `Base`, `Blast` and `Optimism`
- Changes `pointEvaluation` to supported for `Base` and `Optimism`
> feat(opstack): update opcodes

- src/docs/arbitrum-one.mdx
- src/docs/zksync-era.mdx
- src/hooks/useBreadcrumbs.tsx
Updating information for ZKsync Era. Summary:
> feat: updates zksync info

- package.json
- src/components/Breadcrumbs/styles.module.scss
- src/components/Container/styles.module.scss
- src/components/Footer/styles.module.scss
- src/components/Grid/styles.module.scss
- src/components/Hero/styles.module.scss
- src/components/MDXShortcodes/index.tsx
- src/components/Nav/styles.module.scss
- src/components/RollupSummaryCard/styles.module.scss
- src/pages/[slug]/index.tsx
- src/pages/[slug]/styles.module.scss
- src/styles/globals.scss
- Updates `Next` to `15.2.1`
- Updates `React` to `19.0.0`
- Updates `sass` to `1.85.1`
- Removes `react-copy-to-clipboard` since it's not compatible with React 19
- Updates all other dependencies to latest version
- Replaces the deprecated `@import` in `sass` with `@use`
> chore: update dependencies

- src/docs/linea.mdx
Marks `TIMESTAMP` and `NUMBER` as supported opcodes
> feat(linea): Update opcodes

- src/docs/scroll.mdx
Marks `TIMESTAMP` and `NUMBER` as supported opcodes
> feat(scroll): Update opcodes

- src/docs/taiko.mdx
Marks `COINBASE`, `TIMESTAMP`, `NUMBER` and `BASEFEE` as supported opcodes
> feat(taiko): Update opcodes

- src/docs/arbitrum-one.mdx
- Updates the description of `COINBASE` opcode. [source](https://docs.arbitrum.io/build-decentralized-apps/arbitrum-vs-ethereum/solidity-support#differences-from-solidity-on-ethereum)
- Moves the `p256Verify` precompile from the "System contracts" table to the correct, "Precompiled contracts" table
> feat(arbitrum): Update coinbase opcode

- src/docs/base.mdx
- src/docs/blast.mdx
- src/docs/ink.mdx
- src/docs/optimism.mdx
- `eth_getBlockByNumber`, `eth_getTransactionByHash` and `eth_getTransactionReceipt` RPC calls are the same as on ETH
- `eth_newPendingTransactionFilter` is supported by `op-geth`
> feat(opstack): update RPC-API

- src/docs/scroll.mdx
Scroll has transitioned its state trie from zkTrie to Ethereum’s MPT. [source](https://x.com/shenhaichen/status/1912277132627308826)
> feat(scroll): update state trie info

- src/docs/zksync-era.mdx
- Adds information about the EVM bytecode emulator which will be introduced in protocol upgrade v27.
- EVM Emulator enables execution and deployment of contracts compiled with vanilla Solidity and Vyper compilers.
- More info in [ZIP-9 protocol upgrade proposal](https://forum.zknation.io/t/zip-9-v27-evm-emulation-upgrade/626)
This upgrade will be live on ZKsync Era testnet on Apr 1st and mainnet on mid April. We could merge this PR then 🤙
> feat: adds emulator info

- .gitmodules
- src/components/Section/index.tsx
- src/docs/abstract.mdx
- src/docs/zksync-era.mdx
- src/pages/[slug]/index.tsx
- src/utils/types.ts
Adds support for multiple exectution environments of one network. If there is only one chain specification for a network, we assume it is an EVM execution environment. Otherwise we use the last part of the file name to determine the exec env.
Example:
`arbitrum-one.json` => only one chain spec for Arbitrum, it is an EVM chain spec
`[ zk-sync-era_evm.json, zk-sync-era_eravm.json]` => 2 chain specs, one for EVM and one for EraVM
> feat: support multiple execution environments of one network
